import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";
import { EnvironmentProvider } from "@/context/envContext";
import ReactQueryWrapper from "@/components/reactQueryWrapper";
import { QueryClient } from "@tanstack/react-query";
import { getTenants } from "@/queries/getUserDetails";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <ReactQueryWrapper>
        <EnvironmentProvider>
          <Toaster />
          {/* <ThemeProvider
        attribute="class"
        defaultTheme="light"
        enableSystem
        disableTransitionOnChange
      > */}
          <body className={inter.className}>{children}</body>
        </EnvironmentProvider>
      </ReactQueryWrapper>

      {/* </ThemeProvider> */}
    </html>
  );
}
